// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlwPwDqBKgJczlrpVSvYlYcOosALjFruY',
    appId: '1:577806586815:web:c1b9a1834f466020bb470a',
    messagingSenderId: '577806586815',
    projectId: 'flutterfirebase-956bf',
    authDomain: 'flutterfirebase-956bf.firebaseapp.com',
    storageBucket: 'flutterfirebase-956bf.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-aK4qDBocoTwNvdZU7Zwm1f8amgtMc-w',
    appId: '1:577806586815:android:41cdf320cb64c095bb470a',
    messagingSenderId: '577806586815',
    projectId: 'flutterfirebase-956bf',
    storageBucket: 'flutterfirebase-956bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-EX7rsT7GbuWkVZyMTsNE24zcTTHraP4',
    appId: '1:577806586815:ios:c2d8243ed025f8ebbb470a',
    messagingSenderId: '577806586815',
    projectId: 'flutterfirebase-956bf',
    storageBucket: 'flutterfirebase-956bf.appspot.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-EX7rsT7GbuWkVZyMTsNE24zcTTHraP4',
    appId: '1:577806586815:ios:c2d8243ed025f8ebbb470a',
    messagingSenderId: '577806586815',
    projectId: 'flutterfirebase-956bf',
    storageBucket: 'flutterfirebase-956bf.appspot.com',
    iosBundleId: 'com.example.flutterfirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlwPwDqBKgJczlrpVSvYlYcOosALjFruY',
    appId: '1:577806586815:web:1206aff746c9037cbb470a',
    messagingSenderId: '577806586815',
    projectId: 'flutterfirebase-956bf',
    authDomain: 'flutterfirebase-956bf.firebaseapp.com',
    storageBucket: 'flutterfirebase-956bf.appspot.com',
  );
}
